

export default {
    openid: '',
    images: null,
    loading:false,
    // url:'http://pnx7zyyrl.bkt.clouddn.com/',
    url:'http://psbc.ysmine.com/html/',
    showIndexLoadingBar:false,
    loadingProgress:'',
    isPlaying:false,
    preview:false,
    isShare:false,
    head:null,
    keys:[
        'yz-bg',
        'yz-cover-shadow',
        'yz-music-btn',
        'yz-share-btn',
        'yz-qr',
        'yz-cover-shadow',
        'yz-cover',
        'yz-page-border',
        'yz-num-0',
        'yz-num-1',
        'yz-num-2',
        'yz-num-3',
        'yz-num-4',
        'yz-num-5',
        'yz-num-6',
        'yz-num-7',
        'yz-num-8',
        'yz-num-9',
        'yz-page1',
        'yz-page2',
        'yz-page3',
        'yz-page4',
        'yz-page5',
        'yz-page6',
        'yz-page1-left',
        'yz-page2-left',
        'yz-page3-left',
        'yz-page4-left',
        'yz-page5-left',
        'yz-page6-left',
        'yz-page6-btn',
        'yz-share1-bg',
        'yz-share2-bg',
        'yz-share3-bg',
        'yz-share4-bg',
    ]
}
