

export default {
    openid: '',
    images: null,
    loading:false,
    // url:'http://pnx7zyyrl.bkt.clouddn.com/',
    url:'http://cdn.lizikeji.cn/',
    showIndexLoadingBar:true,
    loadingProgress:'',
    isPlaying:false,
    preview:false,
    isShare:false,
    w:'',
    h:'',
    head:null,
    keys:[
        'yz-bg',
        'yz-cover',
        'yz-page-border',
        'yz-page1',
        'yz-page2',
        'yz-page3',
        'yz-page4',
        'yz-page5',
        'yz-page6',
        'yz-page1-left',
        'yz-page2-left',
        'yz-page3-left',
        'yz-page4-left',
        'yz-page5-left',
        'yz-page6-left',
        'yz-page6-btn',
        // 'yz-share1-bg',
        // 'yz-share2-bg',
        // 'yz-share3-bg',
        // 'yz-share4-bg',
    ]
}
